import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), 'database.db')

recipes = [
    {'name': 'Spinach & Mushroom Omelette', 'description': 'High-protein, low-calorie omelette', 'calories': 180, 'protein': 16, 'carbs': 4, 'fats': 12, 'diet_type': 'veg', 'meal_type': 'breakfast', 'ingredients': '3 eggs, 1 cup spinach, 100g mushrooms, salt, pepper', 'instructions': 'Sauté spinach and mushrooms. Pour beaten eggs. Fold when set.', 'prep_time': 5, 'cook_time': 8, 'servings': 1, 'medical_tags': 'high-protein,low-calorie'},
    {'name': 'Poha with Vegetables', 'description': 'Light, fiber-rich breakfast', 'calories': 220, 'protein': 6, 'carbs': 42, 'fats': 4, 'diet_type': 'veg', 'meal_type': 'breakfast', 'ingredients': '1 cup poha, 1 onion, 1 potato, peas, turmeric, mustard seeds', 'instructions': 'Sauté vegetables. Add poha and spices. Mix well.', 'prep_time': 10, 'cook_time': 10, 'servings': 1, 'medical_tags': 'high-fiber,diabetic-friendly'},
    {'name': 'Moong Dal Cheela', 'description': 'Protein-packed, gluten-free', 'calories': 240, 'protein': 14, 'carbs': 28, 'fats': 8, 'diet_type': 'veg', 'meal_type': 'breakfast', 'ingredients': '1 cup moong dal, 1 onion, green chilli, ginger', 'instructions': 'Soak dal. Grind to batter. Cook on griddle with minimal oil.', 'prep_time': 15, 'cook_time': 8, 'servings': 2, 'medical_tags': 'high-protein,gluten-free'},
    {'name': 'Methi Paratha', 'description': 'Iron-rich Indian flatbread', 'calories': 280, 'protein': 10, 'carbs': 38, 'fats': 10, 'diet_type': 'veg', 'meal_type': 'breakfast', 'ingredients': '2 cups wheat flour, 1 bunch methi, salt, oil', 'instructions': 'Mix methi with flour. Knead. Roll and cook on tawa.', 'prep_time': 20, 'cook_time': 15, 'servings': 3, 'medical_tags': 'iron-rich,high-fiber'},
    {'name': 'Dahi with Granola & Berries', 'description': 'Probiotic, antioxidant', 'calories': 200, 'protein': 12, 'carbs': 26, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'breakfast', 'ingredients': '1 cup greek yogurt, 1/4 cup granola, 1/2 cup berries', 'instructions': 'Layer yogurt, berries, and granola. Serve chilled.', 'prep_time': 3, 'cook_time': 0, 'servings': 1, 'medical_tags': 'probiotic,heart-healthy'},
    {'name': 'Egg White Scramble', 'description': 'Ultra-low fat, high protein', 'calories': 140, 'protein': 20, 'carbs': 2, 'fats': 4, 'diet_type': 'non-veg', 'meal_type': 'breakfast', 'ingredients': '4 egg whites, 1 bell pepper, tomato, salt, pepper', 'instructions': 'Scramble egg whites with diced vegetables in non-stick pan.', 'prep_time': 5, 'cook_time': 8, 'servings': 1, 'medical_tags': 'high-protein,low-fat,weight-loss'},
    {'name': 'Chicken Upma', 'description': 'High-protein, whole grain', 'calories': 320, 'protein': 28, 'carbs': 35, 'fats': 8, 'diet_type': 'non-veg', 'meal_type': 'breakfast', 'ingredients': '150g grilled chicken, 1 cup semolina, 1 onion, green chilli', 'instructions': 'Toast semolina. Cook with water. Add shredded chicken.', 'prep_time': 10, 'cook_time': 15, 'servings': 2, 'medical_tags': 'high-protein'},
    {'name': 'Turkey Sausage & Toast', 'description': 'Lean protein breakfast', 'calories': 280, 'protein': 25, 'carbs': 32, 'fats': 7, 'diet_type': 'non-veg', 'meal_type': 'breakfast', 'ingredients': '100g turkey sausage, 2 slices whole grain bread, mustard', 'instructions': 'Grill turkey sausage. Toast bread. Serve with mustard.', 'prep_time': 5, 'cook_time': 10, 'servings': 1, 'medical_tags': 'high-protein,lean'},
    {'name': 'Chia Pudding', 'description': 'Omega-3 rich, plant-based', 'calories': 240, 'protein': 8, 'carbs': 24, 'fats': 12, 'diet_type': 'vegan', 'meal_type': 'breakfast', 'ingredients': '3 tbsp chia seeds, 1 cup almond milk, banana, berries', 'instructions': 'Mix chia seeds with almond milk. Refrigerate overnight. Top with fruit.', 'prep_time': 5, 'cook_time': 0, 'servings': 1, 'medical_tags': 'omega-3,vegan'},
    {'name': 'Banana Oat Pancake', 'description': 'Simple, protein-rich', 'calories': 260, 'protein': 10, 'carbs': 42, 'fats': 6, 'diet_type': 'vegan', 'meal_type': 'breakfast', 'ingredients': '2 bananas, 1 cup oats, 1 tsp vanilla, cinnamon', 'instructions': 'Blend banana and oats. Cook on griddle. Top with berries.', 'prep_time': 10, 'cook_time': 8, 'servings': 2, 'medical_tags': 'plant-based,high-fiber'},
    {'name': 'Tofu Scramble', 'description': 'Complete plant protein', 'calories': 220, 'protein': 18, 'carbs': 12, 'fats': 12, 'diet_type': 'vegan', 'meal_type': 'breakfast', 'ingredients': '200g firm tofu, turmeric, nutritional yeast, vegetables', 'instructions': 'Press tofu. Crumble and cook with turmeric. Add vegetables.', 'prep_time': 10, 'cook_time': 10, 'servings': 1, 'medical_tags': 'vegan,high-protein'},
    {'name': 'Palak Paneer (Low-Fat)', 'description': 'Iron-rich, protein-dense', 'calories': 280, 'protein': 22, 'carbs': 18, 'fats': 12, 'diet_type': 'veg', 'meal_type': 'lunch', 'ingredients': '150g paneer, 2 bunches spinach, tomato, ginger-garlic, oil', 'instructions': 'Blanch spinach. Make puree. Cook paneer in low-fat gravy.', 'prep_time': 20, 'cook_time': 20, 'servings': 2, 'medical_tags': 'iron-rich,high-protein'},
    {'name': 'Dal & Brown Rice', 'description': 'Fiber-rich, diabetic-friendly', 'calories': 350, 'protein': 16, 'carbs': 48, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'lunch', 'ingredients': '1 cup brown rice, 1/2 cup mixed dal, vegetables, spices', 'instructions': 'Cook rice and dal separately. Mix with sautéed vegetables.', 'prep_time': 15, 'cook_time': 35, 'servings': 2, 'medical_tags': 'high-fiber,diabetic-friendly'},
    {'name': 'Baked Falafel Wrap', 'description': 'Plant protein, whole grain', 'calories': 320, 'protein': 14, 'carbs': 42, 'fats': 10, 'diet_type': 'veg', 'meal_type': 'lunch', 'ingredients': '1 cup chickpeas, whole wheat wrap, hummus, vegetables', 'instructions': 'Bake falafel. Assemble wrap with vegetables and hummus.', 'prep_time': 20, 'cook_time': 25, 'servings': 1, 'medical_tags': 'plant-protein,fiber-rich'},
    {'name': 'Vegetable Biryani (Light)', 'description': 'Aromatic, balanced', 'calories': 380, 'protein': 12, 'carbs': 56, 'fats': 10, 'diet_type': 'veg', 'meal_type': 'lunch', 'ingredients': '1 cup basmati rice, 2 cups vegetables, yogurt, spices', 'instructions': 'Layer rice, vegetables, and yogurt. Cook in pot.', 'prep_time': 25, 'cook_time': 30, 'servings': 2, 'medical_tags': 'balanced-macro'},
    {'name': 'Chole Salad', 'description': 'High protein, low calorie', 'calories': 240, 'protein': 14, 'carbs': 32, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'lunch', 'ingredients': '1 cup boiled chickpeas, mixed greens, lemon, cumin', 'instructions': 'Toss chickpeas with salad. Dress with lemon-cumin.', 'prep_time': 10, 'cook_time': 15, 'servings': 1, 'medical_tags': 'high-protein,weight-loss'},
    {'name': 'Tandoori Chicken', 'description': 'Lean, high-protein', 'calories': 280, 'protein': 42, 'carbs': 4, 'fats': 10, 'diet_type': 'non-veg', 'meal_type': 'lunch', 'ingredients': '150g chicken breast, yogurt, tandoori masala, lemon', 'instructions': 'Marinate chicken. Grill until cooked. Serve with salad.', 'prep_time': 30, 'cook_time': 20, 'servings': 1, 'medical_tags': 'high-protein,low-carb'},
    {'name': 'Grilled Fish with Quinoa', 'description': 'Omega-3, heart-healthy', 'calories': 420, 'protein': 38, 'carbs': 42, 'fats': 12, 'diet_type': 'non-veg', 'meal_type': 'lunch', 'ingredients': '150g fish fillet, 1/2 cup quinoa, vegetables, olive oil', 'instructions': 'Grill fish. Cook quinoa. Serve with steamed vegetables.', 'prep_time': 15, 'cook_time': 25, 'servings': 1, 'medical_tags': 'omega-3,heart-healthy'},
    {'name': 'Butter Chicken (Light Version)', 'description': 'Reduced-fat version', 'calories': 350, 'protein': 35, 'carbs': 24, 'fats': 12, 'diet_type': 'non-veg', 'meal_type': 'lunch', 'ingredients': '150g chicken, tomato puree, light cream, spices', 'instructions': 'Cook chicken. Make tomato-based gravy. Use minimal oil.', 'prep_time': 20, 'cook_time': 25, 'servings': 2, 'medical_tags': 'high-protein,reduced-fat'},
    {'name': 'Turkey Meatballs', 'description': 'Lean protein bowl', 'calories': 300, 'protein': 32, 'carbs': 28, 'fats': 8, 'diet_type': 'non-veg', 'meal_type': 'lunch', 'ingredients': '150g ground turkey, oats, egg, vegetables', 'instructions': 'Mix ingredients. Bake meatballs. Serve with brown rice.', 'prep_time': 15, 'cook_time': 25, 'servings': 2, 'medical_tags': 'lean,high-protein'},
    {'name': 'Shrimp Stir Fry', 'description': 'Low-calorie, quick', 'calories': 260, 'protein': 28, 'carbs': 18, 'fats': 10, 'diet_type': 'non-veg', 'meal_type': 'lunch', 'ingredients': '150g shrimp, vegetables, soy sauce, ginger, garlic', 'instructions': 'Stir fry vegetables. Add shrimp. Serve with brown rice.', 'prep_time': 15, 'cook_time': 10, 'servings': 1, 'medical_tags': 'low-calorie,quick-meal'},
    {'name': 'Buddha Bowl', 'description': 'Complete plant nutrition', 'calories': 380, 'protein': 16, 'carbs': 52, 'fats': 12, 'diet_type': 'vegan', 'meal_type': 'lunch', 'ingredients': '1 cup quinoa, chickpeas, sweet potato, kale, tahini', 'instructions': 'Cook grains. Roast vegetables. Assemble and drizzle tahini.', 'prep_time': 20, 'cook_time': 35, 'servings': 1, 'medical_tags': 'plant-based,complete-protein'},
    {'name': 'Tofu & Vegetable Curry', 'description': 'Plant-based protein', 'calories': 320, 'protein': 20, 'carbs': 38, 'fats': 12, 'diet_type': 'vegan', 'meal_type': 'lunch', 'ingredients': '200g tofu, coconut milk, vegetables, spices', 'instructions': 'Marinate tofu. Make coconut-based gravy. Simmer together.', 'prep_time': 20, 'cook_time': 25, 'servings': 2, 'medical_tags': 'vegan,plant-protein'},
    {'name': 'Lentil Soup', 'description': 'High fiber, filling', 'calories': 280, 'protein': 18, 'carbs': 42, 'fats': 6, 'diet_type': 'vegan', 'meal_type': 'lunch', 'ingredients': '1 cup mixed lentils, vegetables, spices, vegetable broth', 'instructions': 'Boil lentils with vegetables and spices until soft.', 'prep_time': 15, 'cook_time': 35, 'servings': 2, 'medical_tags': 'high-fiber,diabetic-friendly'},
    {'name': 'Falafel Plate', 'description': 'Plant protein, satisfying', 'calories': 360, 'protein': 14, 'carbs': 44, 'fats': 14, 'diet_type': 'vegan', 'meal_type': 'lunch', 'ingredients': '1 cup chickpeas, herbs, spices, tahini sauce', 'instructions': 'Make falafel patties. Bake. Serve with hummus and salad.', 'prep_time': 25, 'cook_time': 25, 'servings': 2, 'medical_tags': 'plant-protein,vegan'},
    {'name': 'Vegetable & Bean Chili', 'description': 'High protein, warming', 'calories': 310, 'protein': 16, 'carbs': 48, 'fats': 8, 'diet_type': 'vegan', 'meal_type': 'lunch', 'ingredients': '1 cup mixed beans, vegetables, tomato, spices', 'instructions': 'Sauté vegetables. Add beans and tomato. Simmer 30 min.', 'prep_time': 15, 'cook_time': 40, 'servings': 2, 'medical_tags': 'high-protein,plant-based'},
    {'name': 'Paneer Tikka Masala (Healthy)', 'description': 'Creamy, protein-rich', 'calories': 320, 'protein': 24, 'carbs': 22, 'fats': 14, 'diet_type': 'veg', 'meal_type': 'dinner', 'ingredients': '150g paneer, yogurt, tomato puree, light cream, spices', 'instructions': 'Marinate and grill paneer. Make low-fat tomato gravy.', 'prep_time': 25, 'cook_time': 25, 'servings': 2, 'medical_tags': 'high-protein,balanced'},
    {'name': 'Dal with Roti', 'description': 'Traditional, nutritious', 'calories': 300, 'protein': 14, 'carbs': 48, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'dinner', 'ingredients': '1 cup yellow dal, wheat flour, vegetables, spices', 'instructions': 'Cook dal. Make whole wheat roti. Serve together.', 'prep_time': 20, 'cook_time': 35, 'servings': 2, 'medical_tags': 'high-fiber,iron-rich'},
    {'name': 'Baked Broccoli & Paneer', 'description': 'Low-calorie, protein', 'calories': 240, 'protein': 22, 'carbs': 14, 'fats': 12, 'diet_type': 'veg', 'meal_type': 'dinner', 'ingredients': '150g paneer, 2 cups broccoli, olive oil, garlic, herbs', 'instructions': 'Toss with oil and herbs. Bake at 400°F for 25 minutes.', 'prep_time': 10, 'cook_time': 25, 'servings': 2, 'medical_tags': 'high-protein,low-calorie'},
    {'name': 'Vegetable Khichdi', 'description': 'Light, digestible', 'calories': 280, 'protein': 10, 'carbs': 46, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'dinner', 'ingredients': '1/2 cup rice, 1/4 cup dal, vegetables, ghee, spices', 'instructions': 'Cook rice and dal with vegetables until soft.', 'prep_time': 15, 'cook_time': 30, 'servings': 2, 'medical_tags': 'light-meal,diabetic-friendly'},
    {'name': 'Grilled Salmon & Vegetables', 'description': 'Omega-3 powerhouse', 'calories': 420, 'protein': 40, 'carbs': 24, 'fats': 18, 'diet_type': 'non-veg', 'meal_type': 'dinner', 'ingredients': '150g salmon, broccoli, carrot, olive oil, lemon', 'instructions': 'Grill salmon. Roast vegetables. Serve with lemon.', 'prep_time': 10, 'cook_time': 25, 'servings': 1, 'medical_tags': 'omega-3,heart-healthy'},
    {'name': 'Chicken Tikka Masala (Light)', 'description': 'Spiced, lean protein', 'calories': 340, 'protein': 38, 'carbs': 20, 'fats': 12, 'diet_type': 'non-veg', 'meal_type': 'dinner', 'ingredients': '150g chicken breast, yogurt, tomato, light cream, spices', 'instructions': 'Marinate and grill chicken. Make tomato-based gravy.', 'prep_time': 25, 'cook_time': 25, 'servings': 1, 'medical_tags': 'high-protein,low-fat'},
    {'name': 'Fish Curry', 'description': 'Traditional, healthy', 'calories': 320, 'protein': 35, 'carbs': 22, 'fats': 12, 'diet_type': 'non-veg', 'meal_type': 'dinner', 'ingredients': '150g fish, coconut milk, onion, tomato, spices', 'instructions': 'Make spiced coconut gravy. Add fish. Simmer 15 minutes.', 'prep_time': 15, 'cook_time': 20, 'servings': 2, 'medical_tags': 'omega-3,balanced'},
    {'name': 'Turkey Meatballs with Pasta', 'description': 'Low-fat comfort food', 'calories': 380, 'protein': 32, 'carbs': 44, 'fats': 10, 'diet_type': 'non-veg', 'meal_type': 'dinner', 'ingredients': '150g ground turkey, whole wheat pasta, tomato sauce', 'instructions': 'Bake meatballs. Cook pasta. Top with tomato sauce.', 'prep_time': 15, 'cook_time': 30, 'servings': 2, 'medical_tags': 'lean,whole-grain'},
    {'name': 'Tofu Tikka with Brown Rice', 'description': 'Plant-based protein', 'calories': 340, 'protein': 20, 'carbs': 44, 'fats': 10, 'diet_type': 'vegan', 'meal_type': 'dinner', 'ingredients': '200g firm tofu, yogurt, spices, brown rice, vegetables', 'instructions': 'Marinate tofu. Grill. Serve with brown rice and veggies.', 'prep_time': 25, 'cook_time': 25, 'servings': 2, 'medical_tags': 'vegan,plant-protein'},
    {'name': 'Vegetable Biryani (Vegan)', 'description': 'Aromatic, plant-based', 'calories': 360, 'protein': 12, 'carbs': 56, 'fats': 8, 'diet_type': 'vegan', 'meal_type': 'dinner', 'ingredients': '1 cup basmati rice, vegetables, coconut milk, spices', 'instructions': 'Layer rice and vegetables. Cook until fragrant.', 'prep_time': 25, 'cook_time': 35, 'servings': 2, 'medical_tags': 'vegan,balanced-macro'},
    {'name': 'Lentil & Vegetable Stew', 'description': 'Hearty, nourishing', 'calories': 300, 'protein': 16, 'carbs': 46, 'fats': 8, 'diet_type': 'vegan', 'meal_type': 'dinner', 'ingredients': '1 cup mixed lentils, root vegetables, tomato, herbs', 'instructions': 'Simmer lentils with vegetables and herbs for 40 minutes.', 'prep_time': 20, 'cook_time': 45, 'servings': 2, 'medical_tags': 'high-fiber,plant-protein'},
    {'name': 'Chickpea Curry', 'description': 'Protein-rich, satisfying', 'calories': 320, 'protein': 14, 'carbs': 44, 'fats': 12, 'diet_type': 'vegan', 'meal_type': 'dinner', 'ingredients': '1.5 cups chickpeas, onion, tomato, coconut milk, spices', 'instructions': 'Sauté onions. Add tomato and spices. Add chickpeas.', 'prep_time': 15, 'cook_time': 30, 'servings': 2, 'medical_tags': 'plant-protein,iron-rich'},
    {'name': 'Baked Vegetable Samosa', 'description': 'Healthier snack version', 'calories': 160, 'protein': 4, 'carbs': 22, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'snack', 'ingredients': '1 phyllo sheet, potato, peas, spices', 'instructions': 'Fill phyllo with vegetable mixture. Bake at 375°F.', 'prep_time': 15, 'cook_time': 20, 'servings': 2, 'medical_tags': 'baked,lower-fat'},
    {'name': 'Roasted Chickpea Snack', 'description': 'Crunchy, high-protein', 'calories': 180, 'protein': 10, 'carbs': 22, 'fats': 6, 'diet_type': 'veg', 'meal_type': 'snack', 'ingredients': '1.5 cups chickpeas, paprika, cumin, salt, oil', 'instructions': 'Toss chickpeas with spices. Roast at 400°F 25 minutes.', 'prep_time': 10, 'cook_time': 25, 'servings': 4, 'medical_tags': 'high-protein,crunchy'},
    {'name': 'Paneer & Vegetable Skewers', 'description': 'Protein-rich appetizer', 'calories': 200, 'protein': 16, 'carbs': 8, 'fats': 12, 'diet_type': 'veg', 'meal_type': 'snack', 'ingredients': '100g paneer, bell peppers, onion, yogurt marinade', 'instructions': 'Marinate paneer and vegetables. Grill on skewers.', 'prep_time': 15, 'cook_time': 15, 'servings': 2, 'medical_tags': 'high-protein,low-carb'},
    {'name': 'Vegetable Pakora', 'description': 'Traditional fritter', 'calories': 180, 'protein': 5, 'carbs': 24, 'fats': 8, 'diet_type': 'veg', 'meal_type': 'snack', 'ingredients': '2 cups mixed vegetables, chickpea flour, spices', 'instructions': 'Dip vegetables in batter. Deep fry until golden.', 'prep_time': 10, 'cook_time': 15, 'servings': 4, 'medical_tags': 'traditional'},
    {'name': 'Chicken Tikka Bites', 'description': 'High-protein appetizer', 'calories': 200, 'protein': 24, 'carbs': 4, 'fats': 10, 'diet_type': 'non-veg', 'meal_type': 'snack', 'ingredients': '100g chicken breast, yogurt, spices, bamboo skewers', 'instructions': 'Marinate chicken. Grill. Serve with mint chutney.', 'prep_time': 20, 'cook_time': 12, 'servings': 2, 'medical_tags': 'high-protein,low-carb'},
    {'name': 'Shrimp Pakora', 'description': 'Protein snack', 'calories': 190, 'protein': 16, 'carbs': 18, 'fats': 8, 'diet_type': 'non-veg', 'meal_type': 'snack', 'ingredients': '100g shrimp, chickpea flour, spices', 'instructions': 'Coat shrimp in batter. Deep fry until crispy.', 'prep_time': 15, 'cook_time': 10, 'servings': 2, 'medical_tags': 'high-protein,seafood'},
    {'name': 'Egg Muffins', 'description': 'Portable protein snack', 'calories': 160, 'protein': 14, 'carbs': 2, 'fats': 10, 'diet_type': 'non-veg', 'meal_type': 'snack', 'ingredients': '6 eggs, vegetables, cheese, herbs', 'instructions': 'Mix eggs with vegetables. Bake in muffin tin 20 minutes.', 'prep_time': 10, 'cook_time': 20, 'servings': 6, 'medical_tags': 'high-protein,portable'},
    {'name': 'Hummus & Vegetable Plate', 'description': 'Quick, nutritious', 'calories': 200, 'protein': 8, 'carbs': 24, 'fats': 8, 'diet_type': 'vegan', 'meal_type': 'snack', 'ingredients': '1/2 cup hummus, carrot, cucumber, bell pepper', 'instructions': 'Arrange vegetables around hummus. Serve.', 'prep_time': 5, 'cook_time': 0, 'servings': 2, 'medical_tags': 'quick,plant-protein'},
    {'name': 'Energy Balls (Date & Nuts)', 'description': 'No-bake snack', 'calories': 180, 'protein': 5, 'carbs': 22, 'fats': 10, 'diet_type': 'vegan', 'meal_type': 'snack', 'ingredients': '1 cup dates, 1/2 cup nuts, chia seeds, cocoa', 'instructions': 'Blend dates and nuts. Roll into balls. Chill.', 'prep_time': 15, 'cook_time': 0, 'servings': 8, 'medical_tags': 'vegan,energy-boost'},
    {'name': 'Roasted Nuts & Seeds Mix', 'description': 'Antioxidant snack', 'calories': 220, 'protein': 8, 'carbs': 14, 'fats': 16, 'diet_type': 'vegan', 'meal_type': 'snack', 'ingredients': '1/4 cup almonds, 1/4 cup walnuts, 2 tbsp seeds', 'instructions': 'Mix nuts and seeds. Toast lightly. Store in container.', 'prep_time': 5, 'cook_time': 10, 'servings': 4, 'medical_tags': 'antioxidant,portable'},
    {'name': 'Baked Tofu Chips', 'description': 'Crispy plant snack', 'calories': 160, 'protein': 14, 'carbs': 12, 'fats': 8, 'diet_type': 'vegan', 'meal_type': 'snack', 'ingredients': '200g firm tofu, soy sauce, sesame oil, garlic', 'instructions': 'Press tofu. Cut into chips. Bake at 400°F 25 minutes.', 'prep_time': 15, 'cook_time': 25, 'servings': 3, 'medical_tags': 'plant-protein,crispy'},
    {'name': 'Fruit & Nut Bar', 'description': 'Portable nutrition', 'calories': 200, 'protein': 6, 'carbs': 28, 'fats': 8, 'diet_type': 'vegan', 'meal_type': 'snack', 'ingredients': 'Oats, dates, nuts, coconut oil, vanilla', 'instructions': 'Mix and press into pan. Bake. Cut into bars.', 'prep_time': 15, 'cook_time': 20, 'servings': 12, 'medical_tags': 'portable,whole-food'},
]

def seed_additional_recipes():
    """Insert additional recipe data"""
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}")
        return

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    for recipe in recipes:
        try:
            cur.execute('''
                INSERT INTO recipes (
                    name, description, calories, protein, carbs, fats,
                    diet_type, meal_type, ingredients, instructions,
                    prep_time, cook_time, servings, medical_tags, is_favorite
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                recipe['name'], recipe['description'], recipe['calories'],
                recipe['protein'], recipe['carbs'], recipe['fats'],
                recipe['diet_type'], recipe['meal_type'], recipe['ingredients'],
                recipe['instructions'], recipe['prep_time'], recipe['cook_time'],
                recipe['servings'], recipe['medical_tags'], 0
            ))
        except Exception as e:
            print(f"Error inserting recipe '{recipe['name']}': {e}")

    conn.commit()
    conn.close()
    print(f"Successfully added {len(recipes)} recipes!")

if __name__ == '__main__':
    seed_additional_recipes()
